# fly.toml app configuration file generated for reactivities-jms-1 on 2024-01-26T15:24:21Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivities-jms-1'
primary_region = 'lhr'

[build]
  image = 'jaymslade/reactivities:latest'

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="dhhwrkefe"
  Cloudinary__ApiKey="253482877538342"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
